---
git:
  - https://updates.jenkins-ci.org/download/plugins/git/3.3.0/git.hpi
  - https://updates.jenkins-ci.org/download/plugins/workflow-scm-step/2.4/workflow-scm-step.hpi
  - https://updates.jenkins-ci.org/download/plugins/git-client/2.4.6/git-client.hpi
  - https://updates.jenkins-ci.org/download/plugins/matrix-project/1.11/matrix-project.hpi
  - https://updates.jenkins-ci.org/download/plugins/ssh-credentials/1.13/ssh-credentials.hpi
  - https://updates.jenkins-ci.org/download/plugins/credentials/2.1.13/credentials.hpi
  - https://updates.jenkins-ci.org/download/plugins/mailer/1.20/mailer.hpi
  - https://updates.jenkins-ci.org/download/plugins/structs/1.7/structs.hpi
  - https://updates.jenkins-ci.org/download/plugins/display-url-api/2.0/display-url-api.hpi
  - https://updates.jenkins-ci.org/download/plugins/junit/1.20/junit.hpi
  - https://updates.jenkins-ci.org/download/plugins/script-security/1.27/script-security.hpi
  - https://updates.jenkins-ci.org/download/plugins/github/1.27.0/github.hpi
  - https://updates.jenkins-ci.org/download/plugins/github-api/1.85.1/github-api.hpi
  - https://updates.jenkins-ci.org/download/plugins/plain-credentials/1.4/plain-credentials.hpi
  - https://updates.jenkins-ci.org/download/plugins/token-macro/2.1/token-macro.hpi
  - https://updates.jenkins-ci.org/download/plugins/scm-api/2.1.1/scm-api.hpi
  - https://updates.jenkins-ci.org/download/plugins/support-core/2.41/support-core.hpi
  - https://updates.jenkins-ci.org/download/plugins/docker-commons/1.6/docker-commons.hpi
  - https://updates.jenkins-ci.org/download/plugins/docker-workflow/1.11/docker-workflow.hpi
  - https://updates.jenkins-ci.org/download/plugins/credentials-binding/1.11/credentials-binding.hpi
  - https://updates.jenkins-ci.org/download/plugins/github-branch-source/2.0.6/github-branch-source.hpi
  - https://updates.jenkins-ci.org/download/plugins/workflow-cps-global-lib/2.8/workflow-cps-global-lib.hpi
  - https://updates.jenkins-ci.org/download/plugins/icon-shim/2.0.3/icon-shim.hpi
  - https://updates.jenkins-ci.org/download/plugins/authentication-tokens/1.3/authentication-tokens.hpi
  - https://updates.jenkins-ci.org/download/plugins/git-server/1.7/git-server.hpi
  - https://updates.jenkins-ci.org/download/plugins/pipeline-stage-tags-metadata/1.1.4/pipeline-stage-tags-metadata.hpi
  - https://updates.jenkins-ci.org/download/plugins/pipeline-model-declarative-agent/1.1.1/pipeline-model-declarative-agent.hpi
  - https://updates.jenkins-ci.org/download/plugins/workflow-basic-steps/2.5/workflow-basic-steps.hpi
  - https://updates.jenkins-ci.org/download/plugins/pubsub-light/1.8/pubsub-light.hpi
  - https://updates.jenkins-ci.org/download/plugins/sse-gateway/1.15/sse-gateway.hpi

pipeline:
  -  https://updates.jenkins-ci.org/download/plugins/pipeline-stage-view/2.8/pipeline-stage-view.hpi
  -  https://updates.jenkins-ci.org/download/plugins/workflow-job/2.12/workflow-job.hpi
  -  https://updates.jenkins-ci.org/download/plugins/pipeline-rest-api/2.8/pipeline-rest-api.hpi
  -  https://updates.jenkins-ci.org/download/plugins/momentjs/1.1/momentjs.hpi
  -  https://updates.jenkins-ci.org/download/plugins/jquery-detached/1.2.1/jquery-detached.hpi
  -  https://updates.jenkins-ci.org/download/plugins/handlebars/1.1/handlebars.hpi
  -  https://updates.jenkins-ci.org/download/plugins/workflow-support/2.14/workflow-support.hpi
  -  https://updates.jenkins-ci.org/download/plugins/workflow-api/2.16/workflow-api.hpi
  -  https://updates.jenkins-ci.org/download/plugins/pipeline-graph-analysis/1.3/pipeline-graph-analysis.hpi
  -  https://updates.jenkins-ci.org/download/plugins/pipeline-input-step/2.7/pipeline-input-step.hpi
  -  https://updates.jenkins-ci.org/download/plugins/pipeline-stage-step/2.2/pipeline-stage-step.hpi
  -  https://updates.jenkins-ci.org/download/plugins/groovy/1.30/groovy.hpi
  -  https://updates.jenkins-ci.org/download/plugins/workflow-multibranch/2.15/workflow-multibranch.hpi
  -  https://updates.jenkins-ci.org/download/plugins/workflow-durable-task-step/2.11/workflow-durable-task-step.hpi
  -  https://updates.jenkins-ci.org/download/plugins/branch-api/2.0.9/branch-api.hpi
  -  https://updates.jenkins-ci.org/download/plugins/favorite/2.1.0/favorite.hpi
  -  https://updates.jenkins-ci.org/download/plugins/variant/1.1/variant.hpi
  -  https://updates.jenkins-ci.org/download/plugins/durable-task/1.13/durable-task.hpi
  -  https://updates.jenkins-ci.org/download/plugins/ace-editor/1.1/ace-editor.hpi
  -  https://updates.jenkins-ci.org/download/plugins/jackson2-api/2.7.3/jackson2-api.hpi
  -  https://updates.jenkins-ci.org/download/plugins/metrics/3.1.2.10/metrics.hpi
  -  https://updates.jenkins-ci.org/download/plugins/bouncycastle-api/2.16.1/bouncycastle-api.hpi
  -  https://updates.jenkins-ci.org/download/plugins/pipeline-model-api/1.1.4/pipeline-model-api.hpi
  -  https://updates.jenkins-ci.org/download/plugins/favorite/2.2.0/favorite.hpi
  -  https://updates.jenkins-ci.org/download/plugins/cloudbees-folder/6.0.4/cloudbees-folder.hpi
  -  https://updates.jenkins-ci.org/download/plugins/workflow-step-api/2.11/workflow-step-api.hpi
  -  https://updates.jenkins-ci.org/download/plugins/workflow-cps/2.34/workflow-cps.hpi
  -  https://updates.jenkins-ci.org/download/plugins/pipeline-model-extensions/1.1.4/pipeline-model-extensions.hpi
  -  https://updates.jenkins-ci.org/download/plugins/workflow-cps-global-lib/2.8/workflow-cps-global-lib.hpi
 
blueocean:
  - https://updates.jenkins-ci.org/download/plugins/blueocean/1.0.1/blueocean.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-web/1.0.1/blueocean-web.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-rest/1.0.1/blueocean-rest.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-rest-impl/1.0.1/blueocean-rest-impl.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-pipeline-editor/0.2.0/blueocean-pipeline-editor.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-pipeline-api-impl/1.0.1/blueocean-pipeline-api-impl.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-personalization/1.0.1/blueocean-personalization.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-jwt/1.0.1/blueocean-jwt.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-i18n/1.0.1/blueocean-i18n.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-github-pipeline/1.0.1/blueocean-github-pipeline.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-git-pipeline/1.0.1/blueocean-git-pipeline.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-events/1.0.1/blueocean-events.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-display-url/2.0/blueocean-display-url.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-dashboard/1.0.1/blueocean-dashboard.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-config/1.0.1/blueocean-config.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-commons/1.0.1/blueocean-commons.hpi
  - https://updates.jenkins-ci.org/download/plugins/blueocean-autofavorite/1.0.0/blueocean-autofavorite.hpi
